/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as HealthRouteImport } from './routes/health'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MessageIdRouteImport } from './routes/message.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageIdRoute = MessageIdRouteImport.update({
  id: '/message/$id',
  path: '/message/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/categories': typeof CategoriesRoute
  '/digest': typeof DigestRoute
  '/health': typeof HealthRoute
  '/onboarding': typeof OnboardingRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/message/$id': typeof MessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/categories': typeof CategoriesRoute
  '/digest': typeof DigestRoute
  '/health': typeof HealthRoute
  '/onboarding': typeof OnboardingRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/message/$id': typeof MessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/categories': typeof CategoriesRoute
  '/digest': typeof DigestRoute
  '/health': typeof HealthRoute
  '/onboarding': typeof OnboardingRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/message/$id': typeof MessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/categories'
    | '/digest'
    | '/health'
    | '/onboarding'
    | '/rules'
    | '/search'
    | '/settings'
    | '/message/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/categories'
    | '/digest'
    | '/health'
    | '/onboarding'
    | '/rules'
    | '/search'
    | '/settings'
    | '/message/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/categories'
    | '/digest'
    | '/health'
    | '/onboarding'
    | '/rules'
    | '/search'
    | '/settings'
    | '/message/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CategoriesRoute: typeof CategoriesRoute
  DigestRoute: typeof DigestRoute
  HealthRoute: typeof HealthRoute
  OnboardingRoute: typeof OnboardingRoute
  RulesRoute: typeof RulesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  MessageIdRoute: typeof MessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/$id': {
      id: '/message/$id'
      path: '/message/$id'
      fullPath: '/message/$id'
      preLoaderRoute: typeof MessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CategoriesRoute: CategoriesRoute,
  DigestRoute: DigestRoute,
  HealthRoute: HealthRoute,
  OnboardingRoute: OnboardingRoute,
  RulesRoute: RulesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  MessageIdRoute: MessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
